name: Update data files
run-name: ${{ github.actor }} updated Mapping issue
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-data-files:
    runs-on: ubuntu-22.04
    concurrency:
       group: csv-updates
       cancel-in-progress: true
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11 #install the python needed
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_SUBMITTER: ${{ github.event.issue.user.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python scripts/issues_to_text.py data/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "#$ISSUE_NUMBER: update by $ISSUE_SUBMITTER " || echo "No changes to commit"
          git push
